default: all

bits : bits.cpp
	g++ -Wall bits.cpp -o bits
binary_to_decimal : binary_to_decimal.cpp
	g++ -Wall binary_to_decimal.cpp -o binary_to_decimal
all:
	g++ -Wall bits.cpp -o bits
	g++ -Wall binary_to_decimal.cpp -o binary_to_decimal
	

clean:
	rm bits
	rm binary_to_decimal

