default: all

strings : strings.cpp
	g++ strings.cpp -std=c++0x -o rev_palin
craps : craps.cpp
	g++ craps.cpp -o craps
all:	
	g++ craps.cpp -o craps
	g++ strings.cpp -std=c++0x -o rev_palin

clean:
	rm rev_palin
	rm craps

