default: all
	
prime_debug : prime_debug.cpp
	g++ -Wall prime_debug.cpp -o prime_debug
buggyCode : buggyCode.cpp
	g++ -Wall buggyCode.cpp -o buggyCode
lab3again : lab3again.cpp
	g++ -Wall lab3again.cpp -o lab3again

a3_averages : a3_averages.cpp
	g++ -Wall a3_averages.cpp -o a3_averages

all:
	g++  buggyCode.cpp -o buggyCode
	g++  lab3again.cpp -o lab3again
	g++  prime_debug.cpp -o prime_debug
	g++  a3_averages.cpp -o a3_averages	
clean:
	rm buggyCode
	rm lab3again
	rm prime_debug
	rm a3_averages
